project:
  type: book

book:
  title: "A guide to writing scientific papers using R"
  subtitle: "Research Methodologies 2024"
  author:
   - name: "Rosa Félix"
     email: rosamfelix@tecnico.pt
     url: http://www.rosafelix.bike
     orcid: 0000-0002-5642-6006
     affiliation: "Instituto Superior Técnico - University of Lisbon"
  # date: today
  repo-url: https://github.com/U-Shift/R2Paper
  chapters:
    - href: index.qmd
      text: Home
    - software.qmd
    - rmarkdown.qmd
    - startup.qmd
    - exercise.qmd
    - tips.qmd
    - about.qmd
    - references.qmd
  
  output-file: "R2Paper_2024"
    
  favicon: /images/favicon.png
  sidebar:
    tools:
      - icon: download
        href: https://github.com/U-Shift/R2Paper/releases/download/latest/R2Paper_2024.pdf
        text: "Download PDF"
        target: _blank
        
  page-footer:
    left: "R Félix"
    center: "Research Methodologies"
    right: "December 2024"

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    code-fold: show
    code-tools: true
    number-depth: 3
    toc: true
    toc-expand: 3
    css: styles.css
    
  # pdf:
  #   documentclass: scrreprt


bibliography: references.bib

editor: visual

google-scholar: true
