project:
  type: website

website:
  title: "ResearchMethods24"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - software.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

